version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "08:00"
      timezone: "Asia/Manila"
    commit-message:
      prefix: "[npm] "
    labels:
      - "type/dependencies-updates"
    groups:
      eslint:
        patterns:
          - "eslint"
          - "@eslint/*"
          - "jiti"
          - "@stylistic/*"
          - "typescript-eslint"
      octokit:
        patterns:
          - "@octokit/*"
          - "nock"
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "08:00"
      timezone: "Asia/Manila"
    commit-message:
      prefix: "[actions] "
    labels:
      - "type/dependencies-updates"
